# "Before Using Agoric" dependencies are set up with Docker
# https://agoric.com/documentation/getting-started/before-using-agoric.html
image:
  file: .gitpod.Dockerfile

# Starting a Project
# Ref: https://agoric.com/documentation/getting-started/start-a-project.html
tasks:
  - name: Start Project
    init: |
      cd /workspace && ~/bin/agoric init demo
      cd /workspace/demo && ~/bin/agoric install
  - name: Start the Agoric VM.
    command: cd /workspace/demo && ~/bin/agoric start --reset
  - name: Deploy the Dapp
    command: cd /workspace/demo && ~/bin/agoric deploy ./contract/deploy.js ./api/deploy.js

# vscode:
#   extensions:
#    - bbenoist.Nix
