image:
  file: .gitpod.Dockerfile
tasks:
  - init: >
      # Install agoric-sdk
      git clone https://github.com/Agoric/agoric-sdk
      cd agoric-sdk && yarn install && yarn build
      mkdir -p ~/bin
      cd agoric-sdk && yarn link-cli ~/bin/agoric

      # TODO: Check out demo?

# vscode:
#   extensions:
#    - bbenoist.Nix
