# cribbed from
# https://github.com/gitpod-samples/template-docker-compose/blob/main/.gitpod.yml
tasks:
  - init: |
      docker-compose pull
  - command: |
      docker-compose up


ports:
  - port: 26656
    name: gRPC
    onOpen: ignore
  - port: 26657
    name: RPC
    onOpen: ignore
    visibility: public
  - port: 1317
    name: API
    onOpen: ignore
  - port: 5173
    name: ui
    onOpen: open-preview

vscode:
  extensions:
    - ms-azuretools.vscode-docker
