# cribbed from
# https://github.com/gitpod-samples/template-docker-compose/blob/main/.gitpod.yml
tasks:
  - init: |
      docker-compose pull
  - command: |
      docker-compose up


ports:
  - port: 26656
    onOpen: ignore
  - port: 26657
    onOpen: ignore
  - port: 1317
    onOpen: ignore
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - ms-azuretools.vscode-docker
