# "Before Using Agoric" dependencies are set up with Docker
# https://agoric.com/documentation/getting-started/before-using-agoric.html
image:
  file: .gitpod.Dockerfile

# Starting a Project
# Ref: https://agoric.com/documentation/getting-started/start-a-project.html
tasks:
  - name: Start agd
    init: /workspace/contract/scripts/run-chain.sh


# vscode:
#   extensions:
#    - bbenoist.Nix
