services:
  agd:
    # cf. https://github.com/Agoric/agoric-3-proposals
    image: ghcr.io/agoric/agoric-3-proposals:latest
    platform: linux/amd64
    ports:
      - 26656:26656
      - 26657:26657
      - 1317:1317
    environment:
      DEST: 1
      DEBUG: "SwingSet:ls,SwingSet:vat"
    volumes:
      - .:/workspace
    user: root
    entrypoint: /usr/src/upgrade-test-scripts/start_agd.sh

    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:26657/status |  jq .result.sync_info.latest_block_height"]
      interval: 10s
      timeout: 10s
      retries: 3
